#!/bin/sh
# esht - Embeddable SHell Tags parser thingie
# Licensed under the The Unlicense.
# For more information, please refer to <https://unlicense.org>

# This script should not be sourced, make sure to change the string 'esht'
#   to match this file's name
[ 'esht' = "$( basename ${0} )" ] || return 1

SCRIPT=$( basename "$0" )
VMAJOR=1
VMINOR=3
VPATCH=0
HOMEPAGE="https://gitlab.com/4bcx/esht"
SCRIPT_URL="https://gitlab.com/4bcx/esht/-/raw/dev/esht"
VERSION_URL="https://gitlab.com/4bcx/esht/-/raw/dev/VERSION"
UPDATE_LOCK="/tmp/esht.lock"

if [ -f ${UPDATE_LOCK} ] &&
	[ $( grep -c 'done' ${UPDATE_LOCK} ) -gt 0 ]; then
		printf '%s updated successfully\n' "${0}"
		rm ${UPDATE_LOCK}
		exit 0
fi

print_help () {
	cat << END_OF_HELP_TEXT
${SCRIPT} v${VMAJOR}.${VMINOR}.${VPATCH}
Embeddable SHell Tags parser thingie

Usage: ${SCRIPT} [-x] [-e VAR=VALUE...] SOURCE [OUTPUT]
       ${SCRIPT} -h | -v | -u
Compile SOURCE into shell script OUTPUT or standard output.

Options:
  -h, --help                    display this help text and exit
  -v, --version                 print version and exit
  -x, --execute                 execute the output script
  -e, --env KEY[=VALUE]...      add the definitions KEY=VALUE pairs
                                to the start of the output script
  -m, --meta-data               add meta-data as variables to the output script
  -u, --update                  update ${SCRIPT}

Project homepage: <"${HOMEPAGE}">
END_OF_HELP_TEXT
}

print_version () {
	VERSION="${VMAJOR}.${VMINOR}.${VPATCH}"
	printf '%s Version %s\n' "${SCRIPT}" "${VERSION}"
}

print_error () {
	ERROR_MSG=${1:-Unknown error}
	printf '%s: %s\n' "${SCRIPT}" "${ERROR_MSG}" >&2
}

script_update () {
	if [ -f ${UPDATE_LOCK} ] &&
		[ $( grep -c 'updating' ${UPDATE_LOCK} ) -gt 0 ]; then
			print_error 'Another update process is running'
			exit 1
	fi

	UVERSION_FILE=$( mktemp )
	wget -q -O ${UVERSION_FILE} ${VERSION_URL} 2> /dev/null
	UMAJOR=$( cut -d . -f 1 ${UVERSION_FILE} )
	UMINOR=$( cut -d . -f 2 ${UVERSION_FILE} )
	UPATCH=$( cut -d . -f 3 ${UVERSION_FILE} )
	rm ${UVERSION_FILE}

	if ( [ ${UMAJOR} -gt ${VMAJOR} ] ) || ( [ ${UMAJOR} -eq ${VMAJOR} ] &&
		[ ${UMINOR} -gt ${VMINOR} ] ) || ( [ ${UMAJOR} -eq ${VMAJOR} ] &&
		[ ${UMINOR} -eq ${VMINOR} ] && [ ${UPATCH} -gt ${VPATCH} ] ); then

		printf 'updating\n' > ${UPDATE_LOCK}
		NEW_SCRIPT_FILE=$( mktemp )
		UPDATER_SCRIPT=$( mktemp )
		wget -q -O ${NEW_SCRIPT_FILE} ${SCRIPT_URL} 2> /dev/null

		cat << END_OF_UPDATER_SCRIPT > ${UPDATER_SCRIPT}
cp ${NEW_SCRIPT_FILE} ${0}
rm -f ${NEW_SCRIPT_FILE}
printf 'done\n' > ${UPDATE_LOCK}
exec ${0}
END_OF_UPDATER_SCRIPT

		chmod +x ${NEW_SCRIPT_FILE}
		chmod +x ${UPDATER_SCRIPT}

		exec ${UPDATER_SCRIPT}
	else
		printf 'Already up to date\n'
	fi
}

script_main () {
	BLOCK=''
	PCHAR=''
	STACK=0
	TRAIL=0
	ISIZE=$( wc -c "${INPUT_FILE}" | cut -f 1 -d ' ' )
	
	printf '#!/bin/sh\n' > "${OUTPUT_FILE}"
	if [ "${MMETA}" = 'true' ]; then
		printf 'BASENAME="%s"\n' "$( basename ${INPUT_FILE} )" \
			>> "${OUTPUT_FILE}"
		printf 'DIRNAME="%s"\n' "$( dirname ${INPUT_FILE} )" \
			>> "${OUTPUT_FILE}"
		printf 'GENERATOR="%s"\n' "${SCRIPT}" \
			>> "${OUTPUT_FILE}"
		printf 'VERSION="%s"\n' "${VERSION}" \
			>> "${OUTPUT_FILE}"
		printf 'TIMESTAMP="%s"\n' "$( date -Iseconds )" \
			>> "${OUTPUT_FILE}"
	fi
	printf '%s' "${VARIABLES}" | tr ':' '\n' >> "${OUTPUT_FILE}"

	od -v -c -w1 -Ad "${INPUT_FILE}" | while read -r INDEX ICHAR; do
		if [ "${BLOCK}" = 'shell' ]; then
			if [ "${ICHAR}" = '[' ]; then
				STACK=$(( STACK + 1 ))
			elif [ "${ICHAR}" = ']' ] && [ ${STACK} -eq 0 ]; then
				printf '\n' >> "${OUTPUT_FILE}"
				TRAIL=0
				BLOCK=''
				continue
			elif [ "${ICHAR}" = ']' ] && [ ${STACK} -gt 0 ]; then
				STACK=$(( STACK - 1 ))
			elif [ "${PCHAR}${ICHAR}" = '$[' ] && [ ${STACK} -eq 0 ]; then
				PCHAR='$['
				continue
			elif [ -z "${ICHAR}" ]; then
				TRAIL=$(( TRAIL + 1 ))
				continue
			elif [ -n "${ICHAR}" ] && [ ${TRAIL} -gt 0 ]; then
				printf "%${TRAIL}s" >> "${OUTPUT_FILE}"
				TRAIL=0
			fi

			printf "${ICHAR}" >> "${OUTPUT_FILE}"

		elif [ "${BLOCK}" = 'print' ]; then
			if [ "${ICHAR}" = '\' ]; then
				PCHAR='\'
				continue
			elif [ "${PCHAR}${ICHAR}" = '\$' ]; then
				PCHAR='\$'
				continue
			elif [ "${PCHAR}${ICHAR}" = '\$[' ]; then
				PCHAR='\'
				ICHAR='$['
			elif [ "${ICHAR}" = '$' ]; then
				PCHAR='$'
				continue
			elif [ "${PCHAR}${ICHAR}" = '$[' ]; then
				PCHAR='$['
				printf "'\n" >> "${OUTPUT_FILE}"
				BLOCK='shell'
				continue
			fi

			if [ ${INDEX} -eq ${ISIZE} ]; then
				printf "'\n" >> "${OUTPUT_FILE}"
			else
				printf '%s' "${ICHAR:= }" >> "${OUTPUT_FILE}"
			fi

		else
			if [ "${ICHAR}" = '$' ]; then
				PCHAR='$'
				continue
			elif [ "${PCHAR}${ICHAR}" = '$[' ]; then
				PCHAR='$['
				BLOCK='shell'
				continue
			else
				BLOCK='print'
				printf "printf '" >> "${OUTPUT_FILE}"
				if [ "${PCHAR}" = '$' ]; then
					printf '$' >> "${OUTPUT_FILE}"
				fi
			fi
			printf '%s' "${ICHAR:= }" >> "${OUTPUT_FILE}"
		fi
		
		PCHAR="${ICHAR}"
	done

	if [ "${SHEXE}" = 'true' ]; then
		chmod +x ${OUTPUT_FILE}
		$( realpath ${OUTPUT_FILE} )
	fi

	if [ "${RMOUT}" = 'true' ]; then
		if [ "${SHEXE}" != 'true' ]; then
			cat "${OUTPUT_FILE}"
		fi
		rm "${OUTPUT_FILE}"
	fi
}

SHEXE='false'
DEFKV='false'
RMOUT='false'
MMETA='false'

if [ $# -eq 0 ]; then
	print_error "Missing source filename"
	print_help >&2
	exit 5
else
	while [ $# -gt 0 ]; do
		case "${1}" in
			-h|--help)
				print_help
				exit 0
				;;
			-v|--version)
				print_version
				exit 0
				;;
			-x|--execute)
				SHEXE='true'
				DEFKV='false'
				;;
			-e|--env)
				DEFKV='true'
				;;
			-m|--meta-data)
				MMETA='true'
				DEFKV='false'
				;;
			-u|--update)
				script_update
				exit 0
				;;
			--)
				DEFKV='false'
				;;
			-*)
				print_error "${1}: Invalid argument"
				print_help >&2
				exit 22
				;;
			*)
				if [ "${DEFKV}" = 'true' ]; then
					KEY="${1%%=*}"
					VALUE="${1#${KEY}}"
					VALUE="${VALUE#=}"
					SANE_KEY="$( printf '%s' ${KEY#[0-9]} \
						| tr -dc [0-9a-zA-Z_] )"
					if [ "${KEY}" = "${SANE_KEY}" ]; then
						VARIABLES="${VARIABLES}${KEY}=\"${VALUE}\":"
					else
						print_error "${KEY}: Invalid argument"
						print_help >&2
						exit 22
					fi
				else
					if [ -z "${INPUT_FILE}" ]; then
						INPUT_FILE="${1}"
					else
						if [ -z "${OUTPUT_FILE}" ]; then
							OUTPUT_FILE="${1}"
						else
							print_error "${1}: Too many files specified"
							print_help >&2
							exit 22
						fi
					fi
				fi
				;;
		esac
		shift
	done
fi

if [ ! -f "${INPUT_FILE}" ]; then
	print_error "${INPUT_FILE}: File cannot be opened or does not exist"
	exit 2
fi

if [ -f "${OUTPUT_FILE}" ]; then
	print_error "${2}: File exists and will be overwritten"
else
	if [ -z "${OUTPUT_FILE}" ]; then
		OUTPUT_FILE=$( mktemp )
		RMOUT='true'
	fi
fi

trap "print_error 'Interrupt signal detected, output may be incomplete'" INT

script_main
